// The product feed the Meta catalogue reads, built on each request from
// products.js.
//
// It used to be a file generated by tools/catalog.ps1 and pushed. That put a
// manual step between a sale and the catalogue knowing about it, and with 22
// of the 38 colours one of a kind, the window between selling a pair and
// remembering to run the script is exactly when Meta would keep advertising
// it. Generated here, the feed cannot be stale: whatever Meta fetches is what
// products.js says at that moment.
//
// Served at /meta-feed.csv through a rewrite in _redirects, because that is the
// address already registered in Commerce Manager.

const CATALOGUE = require("../../products.js");
const { I18N } = require("../../i18n.js");

const SITE = "https://rumorlupas.com";

// Meta treats this as a claim about the goods, and Marcos confirmed on
// 2026-08-20 that they are sold as new. It is not a claim about authenticity.
const CONDITION = "new";

const PT = I18N.pt;

// One row per colour, not per model. A catalogue that only knew "Juliet" would
// go on advertising one that is gone in blue and left only in grey; item_group_id
// is what ties them back together as variants of a single product.
const COLUMNS = [
  "id", "item_group_id", "title", "description", "availability", "condition",
  "price", "link", "image_link", "additional_image_link", "brand", "color",
  "quantity_to_sell_on_facebook", "google_product_category",
  "custom_label_0", "custom_label_1",
];

function csv(value) {
  const v = value == null ? "" : String(value);
  return /[",\r\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

function colorLabel(color) {
  return PT[`color.${color.id}`] || color.name || "";
}

function rowsFor(product) {
  const slug = CATALOGUE.productSlug(product);
  const story = PT[`history.${product.id}`] || "";
  const variants = (product.colors && product.colors.length) ? product.colors : [null];

  return variants.map((color) => {
    const images = (color ? color.images : product.images) || [];
    // Meta rejects an item with no image, and a model still waiting for its
    // shoot has none. Better absent than rejected.
    if (!images.length) return null;

    const stock = color ? color.stock : undefined;
    const tracked = typeof stock === "number";
    const label = color ? colorLabel(color) : "";

    return [
      color ? `${product.id}|${color.id}` : product.id,
      product.id,
      label ? `Oakley ${product.name} - ${label}` : `Oakley ${product.name}`,
      story,
      !tracked || stock > 0 ? "in stock" : "out of stock",
      CONDITION,
      // Meta wants a dot, and toFixed gives one regardless of where the server
      // happens to think it is.
      `${product.price.toFixed(2)} EUR`,
      `${SITE}/lupas/${slug}${color ? `?cor=${color.id}` : ""}`,
      // The head-on shot is always first in a colour's own list.
      `${SITE}/${images[0]}`,
      images.slice(1, 20).map((img) => `${SITE}/${img}`).join(","),
      "Oakley",
      label,
      tracked ? String(stock) : "",
      "178",
      // Labels exist so product sets can be built in Commerce Manager without
      // listing ids by hand: one set per model, and one of everything that is
      // down to its last unit.
      product.name,
      tracked && stock === 1 ? "unidade unica" : "",
    ].map(csv).join(",");
  }).filter(Boolean);
}

exports.handler = async () => {
  try {
    const rows = CATALOGUE.PRODUCTS.flatMap(rowsFor);
    const body = [COLUMNS.join(","), ...rows].join("\n") + "\n";

    return {
      statusCode: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        // Meta refetches on its own schedule; a short cache keeps a burst of
        // requests off the function without letting a sale go unnoticed for
        // long. Nothing here is per-visitor, so it is safe to share.
        "Cache-Control": "public, max-age=300",
      },
      body,
    };
  } catch (err) {
    // A 500 makes Meta keep the last good feed and retry, which is the safe
    // failure: a 200 with a broken body would empty the catalogue.
    console.error("meta-feed failed:", err);
    return { statusCode: 500, body: "feed unavailable" };
  }
};
