const PRODUCTS = [
  {
    id: "eye-jacket-45",
    name: "Eye Jacket Redux",
    price: 45,
    history: "Lançado em 1996, o Eye Jacket foi um dos modelos que definiu a estética esportiva da Oakley nos anos 90, com sua lente envolvente e visual futurista. Rapidamente virou item de estilo fora das pistas, adotado pela cena rave e pelo streetwear da época. Essa versão \"Redux\" resgata a silhueta original com acabamento atualizado.",
    images: [
      "images/products/eye-jacket-45/2.avif",
      "images/products/eye-jacket-45/1.avif",
      "images/products/eye-jacket-45/3.avif",
      "images/products/eye-jacket-45/4.avif",
      "images/products/eye-jacket-45/5.avif",
      "images/products/eye-jacket-45/6.webp",
      "images/products/eye-jacket-45/model.jpg",
    ],
  },
  {
    id: "plantaris-50",
    name: "Plantaris",
    price: 50,
    history: "O Plantaris representa a leitura mais recente da Oakley sobre o formato wrap clássico da marca, com maior cobertura lateral e um encaixe pensado tanto para performance quanto para o dia a dia. Une a herança esportiva da marca a um visual mais contemporâneo.",
  },
  {
    id: "juliet-45",
    name: "Juliet",
    price: 45,
    history: "A Juliet integra a lendária linha X-Metal da Oakley, lançada no fim dos anos 90 e batizada em referência ao desenho técnico das lentes. Com armação metálica e visual arrojado, tornou-se peça cult no automobilismo e no streetwear, sendo um dos modelos mais colecionados da marca até hoje.",
  },
  {
    id: "xx-45",
    name: "XX",
    price: 45,
    history: "O XX segue a linguagem geométrica e metálica que consagrou a família X-Metal da Oakley, com uma proposta ainda mais compacta e angular. Um modelo para quem busca o visual técnico da marca em um formato mais discreto.",
  },
  {
    id: "plate-55",
    name: "Plate",
    price: 55,
    history: "O Plate aposta em uma armação mais robusta e um visual urbano, afastando-se da estética puramente esportiva da Oakley em direção ao dia a dia da cidade sem abandonar a durabilidade que a marca é conhecida por entregar.",
  },
  {
    id: "gascan-50",
    name: "Gascan",
    price: 50,
    history: "Introduzido no início dos anos 2000, o Gascan é hoje um dos formatos mais duradouros do catálogo Oakley — simples, versátil e igualmente à vontade na praia, na cidade ou na trilha. Sua permanência em produção por mais de duas décadas é rara entre os modelos da marca.",
  },
  {
    id: "splice-53",
    name: "Splice",
    price: 53,
    history: "O Splice combina uma armação semi-arredondada com lente ampla, equilibrando o DNA esportivo da Oakley com um visual mais suave, pensado para quem quer proteção solar sem abrir mão do conforto no uso prolongado.",
  },
  {
    id: "monster-dog-47",
    name: "Monster Dog",
    price: 47,
    history: "O Monster Dog nasceu da fase mais experimental do design da Oakley nos anos 2000, com uma armação larga e presença marcante. Um modelo para quem não tem medo de um visual mais ousado.",
  },
  {
    id: "dartboard-50",
    name: "Dartboard",
    price: 50,
    history: "O Dartboard traz uma lente circular ampla sobre uma armação leve, equilibrando um visual retrô com a tecnologia de lentes que a Oakley desenvolveu para uso esportivo intenso.",
  },
  {
    id: "flak-2xl-45",
    name: "Flak 2.0 XL",
    price: 45,
    history: "O Flak é uma das siluetas mais populares e duradouras da Oakley, adotado amplamente no ciclismo e no atletismo pela estabilidade e campo de visão. A versão 2.0 XL amplia o encaixe para rostos maiores, mantendo a mesma proposta de performance.",
  },
  {
    id: "pitboss-53",
    name: "PitBoss",
    price: 53,
    history: "O PitBoss é um resgate de um dos formatos mais robustos do catálogo Oakley do início dos anos 2000, com armação espessa e presença forte — um visual que remete diretamente à estética \"Y2K\" que voltou às ruas nos últimos anos.",
  },
];
