const PRODUCTS = [
  { id: "eye-jacket-45",   name: "Oakley Eye Jacket",     price: 45, images: [
      "images/products/eye-jacket-45/2.avif",
      "images/products/eye-jacket-45/1.avif",
      "images/products/eye-jacket-45/3.avif",
      "images/products/eye-jacket-45/4.avif",
      "images/products/eye-jacket-45/5.avif",
      "images/products/eye-jacket-45/6.webp",
      "images/products/eye-jacket-45/model.jpg",
    ] },
  { id: "plantaris-50",    name: "Oakley Plantaris",      price: 50 },
  { id: "juliet-45",       name: "Oakley Juliet",         price: 45 },
  { id: "xx-45",           name: "Oakley XX",             price: 45 },
  { id: "plate-55",        name: "Oakley Plate",          price: 55 },
  { id: "gascan-50",       name: "Oakley Gascan",         price: 50 },
  { id: "splice-53",       name: "Oakley Splice",         price: 53 },
  { id: "monster-dog-47",  name: "Oakley Monster Dog",    price: 47 },
  { id: "dartboard-50",    name: "Oakley Dartboard",      price: 50 },
  { id: "flak-2xl-45",     name: "Oakley Flak 2.0 XL",    price: 45 },
  { id: "pitboss-53",      name: "Oakley PitBoss",        price: 53 },
];
