# Rebuilds sitemap.xml and _redirects from products.js, so neither has to be
# kept in step by hand. Run it after adding, removing or renaming a product:
#
#   .\tools\sitemap.ps1
#
# Renaming matters: the address is derived from the model's name, so a rename
# changes the URL and the old one needs to keep redirecting.
param(
  [string]$Root = ".",
  [string]$Site = "https://rumorlupas.com"
)

$source = [System.IO.File]::ReadAllText(
  (Resolve-Path (Join-Path $Root "products.js")), [System.Text.Encoding]::UTF8)

# Only product-level entries: colour ids sit deeper, and the file's comments
# carry an example id that must not be picked up.
$block = [regex]::Match($source, 'const PRODUCTS = \[(.*?)\n\];', 'Singleline').Groups[1].Value
$block = [regex]::Replace($block, '(?m)^\s*//.*$', '')

$products = @()
foreach ($m in [regex]::Matches($block, '(?m)^\s{2,4}(\{ )?id: "([a-z0-9.-]+)",\s*\r?\n?\s*name: "([^"]+)"')) {
  $slug = $m.Groups[3].Value.ToLowerInvariant()
  $slug = $slug.Normalize([Text.NormalizationForm]::FormD) -replace '\p{Mn}', ''
  $slug = ($slug -replace '[^a-z0-9]+', '-').Trim('-')
  $products += [pscustomobject]@{ id = $m.Groups[2].Value; slug = "oakley-$slug" }
}

$dupes = $products | Group-Object slug | Where-Object { $_.Count -gt 1 }
if ($dupes) { throw "Slugs repetidos: " + ($dupes.Name -join ', ') }

# ---------- sitemap.xml ----------
$today = (Get-Date).ToString("yyyy-MM-dd")
$lines = @('<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
function Add-Url([string]$loc, [string]$priority, [string]$freq) {
  $script:lines += "  <url>", "    <loc>$loc</loc>", "    <lastmod>$today</lastmod>",
                   "    <changefreq>$freq</changefreq>", "    <priority>$priority</priority>", "  </url>"
}
Add-Url "$Site/" "1.0" "daily"
foreach ($p in $products) { Add-Url "$Site/lupas/$($p.slug)" "0.8" "weekly" }
Add-Url "$Site/termos.html" "0.2" "yearly"
Add-Url "$Site/privacidade.html" "0.2" "yearly"
$lines += '</urlset>'
[System.IO.File]::WriteAllText((Join-Path $Root "sitemap.xml"),
  ($lines -join "`n") + "`n", (New-Object System.Text.UTF8Encoding($false)))

# ---------- _redirects ----------
# Order matters: Netlify takes the first rule that matches. The 301s carry "!"
# so they beat produto.html actually existing on disk.
$r = @(
  "# Generated by tools/sitemap.ps1 - do not edit by hand.",
  "",
  "# The address each model was sold at before /lupas/ existed. Kept because it",
  "# is in the sitemap Google already fetched and in links people have shared.")
foreach ($p in $products) { $r += "/produto.html  id=$($p.id)  /lupas/$($p.slug)  301!" }
$r += "", "# Serve the product page at its own address without changing the bar.",
      "/lupas/*  /produto.html  200"
[System.IO.File]::WriteAllText((Join-Path $Root "_redirects"),
  ($r -join "`n") + "`n", (New-Object System.Text.UTF8Encoding($false)))

"sitemap.xml : {0} modelos, {1} urls" -f $products.Count, ($products.Count + 3)
"_redirects  : {0} redirecionamentos + 1 reescrita" -f $products.Count
