# Rebuilds sitemap.xml and _redirects from products.js, so neither has to be
# kept in step by hand. Run it after adding, removing or renaming a product:
#
#   .\tools\sitemap.ps1
#
# Renaming matters: the address is derived from the model's name, so a rename
# changes the URL and the old one needs to keep redirecting.
param(
  [string]$Root = ".",
  [string]$Site = "https://rumorlupas.com"
)

# Models pulled from sale but expected back. Their pages are gone, so both the
# old and the new address are sent to the catalogue with a 302 - a temporary
# code, because a 301 tells Google the address is finished for good and it
# would have to earn its place again on the way back. Without this, produto.html
# still answers 200 and shows "produto nao encontrado", which reads to Google
# as a broken page rather than a deliberate one.
$RETIRED = @(
  @{ id = "splice-53"; slug = "oakley-splice" }
)

$source = [System.IO.File]::ReadAllText(
  (Resolve-Path (Join-Path $Root "products.js")), [System.Text.Encoding]::UTF8)

# Only product-level entries: colour ids sit deeper, and the file's comments
# carry an example id that must not be picked up.
$block = [regex]::Match($source, 'const PRODUCTS = \[(.*?)\n\];', 'Singleline').Groups[1].Value
$block = [regex]::Replace($block, '(?m)^\s*//.*$', '')

$products = @()
foreach ($m in [regex]::Matches($block, '(?m)^\s{2,4}(\{ )?id: "([a-z0-9.-]+)",\s*\r?\n?\s*name: "([^"]+)"')) {
  $slug = $m.Groups[3].Value.ToLowerInvariant()
  $slug = $slug.Normalize([Text.NormalizationForm]::FormD) -replace '\p{Mn}', ''
  $slug = ($slug -replace '[^a-z0-9]+', '-').Trim('-')
  $products += [pscustomobject]@{ id = $m.Groups[2].Value; slug = "oakley-$slug" }
}

$dupes = $products | Group-Object slug | Where-Object { $_.Count -gt 1 }
if ($dupes) { throw "Slugs repetidos: " + ($dupes.Name -join ', ') }

# ---------- languages ----------
# Portuguese keeps the bare paths; the other two sit under a prefix. Must match
# DEFAULT_LANG and localePath() in i18n.js.
$LANGS = @("pt", "en", "es")
$HREFLANG = @{ pt = "pt-PT"; en = "en"; es = "es" }

function Loc-Path([string]$bare, [string]$lang) {
  if ($lang -eq "pt") { return $bare }
  if ($bare -eq "/") { return "/$lang/" }
  return "/$lang$bare"
}

# ---------- sitemap.xml ----------
$today = (Get-Date).ToString("yyyy-MM-dd")
$lines = @('<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">')

$pages = @()
function Add-Page([string]$path, [string]$priority, [string]$freq, [string[]]$langs = $LANGS) {
  $script:pages += [pscustomobject]@{
    path = $path; priority = $priority; freq = $freq; langs = $langs }
}
Add-Page "/" "1.0" "daily"
foreach ($p in $products) { Add-Page "/lupas/$($p.slug)" "0.8" "weekly" }
# Portuguese only: the documents themselves are not translated, and the notice
# at the top of each says only the Portuguese version is binding. Must match
# PT_ONLY in i18n.js.
Add-Page "/termos.html" "0.2" "yearly" @("pt")
Add-Page "/privacidade.html" "0.2" "yearly" @("pt")

# Each language gets an entry of its own - a page can only be found in a
# language it has an address in - and every entry lists all three, so Google
# reads them as one page rather than three competing for the same searches.
foreach ($page in $pages) {
  foreach ($lang in $page.langs) {
    $lines += "  <url>"
    $lines += "    <loc>$Site$(Loc-Path $page.path $lang)</loc>"
    if ($page.langs.Count -gt 1) {
      foreach ($alt in $page.langs) {
        $lines += '    <xhtml:link rel="alternate" hreflang="{0}" href="{1}{2}"/>' -f
                  $HREFLANG[$alt], $Site, (Loc-Path $page.path $alt)
      }
      $lines += '    <xhtml:link rel="alternate" hreflang="x-default" href="{0}{1}"/>' -f
                $Site, (Loc-Path $page.path "pt")
    }
    $lines += "    <lastmod>$today</lastmod>", "    <changefreq>$($page.freq)</changefreq>",
              "    <priority>$($page.priority)</priority>", "  </url>"
  }
}
$urlCount = ($pages | ForEach-Object { $_.langs.Count } | Measure-Object -Sum).Sum
$lines += '</urlset>'
[System.IO.File]::WriteAllText((Join-Path $Root "sitemap.xml"),
  ($lines -join "`n") + "`n", (New-Object System.Text.UTF8Encoding($false)))

# ---------- _redirects ----------
# Order matters: Netlify takes the first rule that matches. The 301s carry "!"
# so they beat produto.html actually existing on disk.
$r = @(
  "# Generated by tools/sitemap.ps1 - do not edit by hand.",
  "",
  "# The address each model was sold at before /lupas/ existed. Kept because it",
  "# is in the sitemap Google already fetched and in links people have shared.")
foreach ($p in $products) { $r += "/produto.html  id=$($p.id)  /lupas/$($p.slug)  301!" }

# Before the catch-all below, or /lupas/<retirado> would be rewritten to
# produto.html and answer 200 with "produto nao encontrado".
if ($RETIRED.Count) {
  $r += "", "# Pulled from sale, expected back: 302 and not 301, so the address is not",
        "# written off. Each language goes to its own catalogue."
  foreach ($x in $RETIRED) {
    $r += "/produto.html  id=$($x.id)  /  302!"
    $r += "/lupas/$($x.slug)  /  302!"
    foreach ($lang in $LANGS | Where-Object { $_ -ne "pt" }) {
      $r += "/$lang/lupas/$($x.slug)  /$lang/  302!"
    }
  }
}

# The model rules come before the catch-all, or /en/lupas/x would be rewritten
# to /lupas/x, which is not a file on disk and would 404.
$r += "", "# Serve the product page at its own address without changing the bar."
foreach ($lang in $LANGS | Where-Object { $_ -ne "pt" }) {
  $r += "/$lang/lupas/*  /produto.html  200"
}
$r += "/lupas/*  /produto.html  200"

$r += "", "# The Meta catalogue feed. Generated per request from products.js rather",
      "# than kept as a file, so a sale cannot leave a sold pair being advertised",
      "# until someone remembers to regenerate it. The address is the one already",
      "# registered in Commerce Manager, so it has to keep working."
$r += "/meta-feed.csv  /.netlify/functions/meta-feed  200"

$r += "", "# The translated addresses are the same files, read in another language:",
      "# i18n.js takes the language from the prefix that is still in the address bar.",
      "# Netlify ignores the trailing slash when it matches, so the first rule",
      "# answers both /en and /en/. Do not add a /en -> /en/ redirect: it matches",
      "# /en/ as well and the address redirects to itself, forever."
foreach ($lang in $LANGS | Where-Object { $_ -ne "pt" }) {
  $r += "/$lang/  /index.html  200", "/$lang/*  /:splat  200"
}
[System.IO.File]::WriteAllText((Join-Path $Root "_redirects"),
  ($r -join "`n") + "`n", (New-Object System.Text.UTF8Encoding($false)))

"sitemap.xml : {0} modelos, {1} paginas, {2} urls em {3} linguas" -f
  $products.Count, $pages.Count, $urlCount, $LANGS.Count
$rules = $r | Where-Object { $_ -match '\s(200|30\d!?)$' }
"_redirects  : {0} redirecionamentos + {1} reescritas" -f
  @($rules | Where-Object { $_ -match '30\d!?$' }).Count,
  @($rules | Where-Object { $_ -match '200$' }).Count
